//! Subcommand implementations.

pub mod backup;
pub mod commit;
pub mod embed;
pub mod forget_sweep;
pub mod generate_auth_token;
pub mod init;
pub mod install_hooks;
pub mod install_mcp;
pub mod lint;
pub mod llm_test;
pub mod render_shared;
pub mod reset;
pub mod restore;
pub mod search;
pub mod serve;
pub mod setup_agent;
pub mod status;
pub mod watch;
pub mod write_page;
